### ISSUE TITLE
book linking 

### ISSUE THREAD

**Issue by fatmalshamsi** [RanimHilal/BookWorld#7]
hey guys for the lists do you think it's better to make the link as the book name or the image as a link. if you prefer the image as link please show me the code on how can i do it. 
![Capture](https://user-images.githubusercontent.com/115168712/202921065-9cfae5c9-bbc3-473e-b67d-e0e206516991.PNG)

**Comment by RanimHilal** [comment]
it would look better by putting only image without the title so use image as link. and by using this way <a href="#pagelink"><img src="imagelink" alt="......." height=.. width=..></a>. 
also try to change the padding of the image

**Comment by RanimHilal** [comment]
<a href="pagelink><img src="image" alt="...." height=,, width=,,,></a  
 close it with >

**Comment by RanimHilal** [comment]
![Screenshot (511)](https://user-images.githubusercontent.com/113409429/202921571-f42d6b79-2ce0-4d5c-8b29-aa459daa1a6c.png)

**Comment by fatmalshamsi** [comment]
> 
thanks bae will do
